name:                wav-metadata-service
version:             0.1.0.0
github:              "michaelheyman/wav-metadata-service"
license:             BSD3
author:              "Michael Heyman"
maintainer:          "michaelheyman@users.noreply.github.com"
copyright:           "(c) 2020 Michael Heyman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            WAV metadata service
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/michaelheyman/wav-metadata-service#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- haskell-wav
- servant-server
- servant-multipart
- wai
- warp

library:
  source-dirs: src

executables:
  wav-metadata-service-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wav-metadata-service

tests:
  wav-metadata-service-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wav-metadata-service
